[build]
  publish= "public"
  Command = "npm run build"
# [functions]
#   directory = "lambda"
# [dev]
#   functions = "src/lambda"
#   functionsPort = "7000"
# CSP:
[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-r@nd0m' 'strict-dynamic' fastly.net *.fastly.net lr-ingest.io *.lr-ingest.io cloudfront.net *.cloudfront.net googletagmanager.com *.googletagmanager.com *.google-analytics.com; worker-src 'self' blob: data: lr-ingest.io *.lr-ingest.io; prefetch-src 'self'; connect-src 'self' r.lr-in.com lr-ingest.io *.lr-ingest.io google-analytics.com *.google-analytics.com stats.g.doubleclick.net; img-src 'self' thepmgroup.flywheelsites.com *.fastly.net fastly.net data: cloudfront.net *.cloudfront.net cloudinary.com *.cloudinary.com google.com www.google.com google-analytics.com *.google-analytics.com; font-src 'self' gstatic.com *.gstatic.com cloudfront.net *.cloudfront.net data:; manifest-src 'self'; style-src 'unsafe-inline' googleapis.com *.googleapis.com cloudfront.net *.cloudfront.net; frame-ancestors 'self'; form-action 'self'; script-src-elem 'self' netlify-cdp-loader.netlify.app 'unsafe-inline' cdn.lr-in.com lr-ingest.io r.lr-in.com *.lr-ingest.io cloudfront.net *.cloudfront.net googletagmanager.com *.googletagmanager.com google-analytics.com *.google-analytics.com; object-src 'self' 'none'; report-uri github.com/NoisyTrumpet/the-pm-group/issues"
[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  # baseUrl = "https://thepmgrp.com"
  trailingSlash = true
  exclude = [
    # By file Path
    "./public/news/2/index.html",
    "./public/news/3/index.html",
    "./public/news/4/index.html",
    "./public/news/5/index.html",
    "./public/news/6/index.html",
    "./public/news/7/index.html",
    "./public/news/8/index.html",
    "./public/news/9/index.html",
    "./public/news/10/index.html",
    "./public/news/11/index.html",
    "./public/news/12/index.html",
    "./public/news/13/index.html",
    "./public/news/14/index.html",
    "./public/news/15/index.html",
    "./public/news/16/index.html",
    "./public/news/17/index.html",
    "./public/news/18/index.html",
    "./public/news/19/index.html",
    "./public/news/20/index.html",
    "./public/news/21/index.html",
    "./public/news/22/index.html",
    "./public/news/23/index.html",
    "./public/news/24/index.html",
    "./public/news/25/index.html",
    "./public/news/26/index.html",
    "./public/news/27/index.html",
    "./public/news/28/index.html",
    "./public/news/29/index.html",
    "./public/our-work/uncategorized/index.html",
    "./public/404/index.html",
    "./public/404.html",
  ]
[[plugins]]
    package = "@netlify/plugin-gatsby"
[[redirects]]
  from = "/agency-news"
  to = "/news/"
[[redirects]]
  from = "/works"
  to = "/our-work/"
[[redirects]]
  from = "/capabilities"
  to = "/expertise/"
[[redirects]]
  from = "/agency-news/drive-away-for-education-2021/"
  to = "/news/drive-away-for-education-fundraiser-aims-to-assist-50000-children-this-year/"
[[redirects]]
  from = "/agency-news/sjrc-texas/"
  to = "/news/making-a-difference-in-san-antonio-sjrc/"
[[redirects]]
  from = "/agency-news/us-inflation-rises/"
  to = "/news/the-price-of-everything-appears-to-be-rising-as-inflation-grips-america-post-pandemic/"
[[redirects]]
  from = "/ihop-aid-veterans-families-throughout-november"
  to = "/news/ihop-aid-veterans-families-throughout-november/"
[[redirects]]
  from = "/news/black-friday"
  to = "/news/black-friday/"
[[redirects]]
  from = "news/1-trillion-holiday-retail-sales"
  to = "news/1-trillion-holiday-retail-sales/"
[[redirects]]
  from = "/thanksgiving-black-friday-2017-become-one-busiest-online-shopping-weeks-history"
  to = "/news/thanksgiving-black-friday-2017-become-one-busiest-online-shopping-weeks-history/"
[[redirects]]
  from = "/four-ways-marketing-provides-value"
  to = "/news/four-ways-marketing-provides-value/"
[[redirects]]
  from = "/thomas-j-henry-continues-turkey-giveaway-tradition/"
  to = "/news/thomas-j-henry-continues-turkey-giveaway-tradition/"
[[redirects]]
  from = "/jersey-advertising-arrives-nba/"
  to = "/news/jersey-advertising-arrives-nba/"
[[redirects]]
  from = "/agency-news/pm-group-supports-100-club/"
  to = "/news/agency-donates-10000-to-100-club/"
[[redirects]]
  from = "/agency-news/*"
  to = "/news/:splat/"
