[[redirects]]
  from = "/agency-news"
  to = "/news/"
[[redirects]]
  from = "/works"
  to = "/our-work/"
[[redirects]]
  from = "/capabilities"
  to = "/expertise/"
[[redirects]]
  from = "/agency-news/drive-away-for-education-2021/"
  to = "/news/drive-away-for-education-fundraiser-aims-to-assist-50000-children-this-year/"
[[redirects]]
  from = "/agency-news/sjrc-texas/"
  to = "/news/making-a-difference-in-san-antonio-sjrc/"
[[redirects]]
  from = "/agency-news/us-inflation-rises/"
  to = "/news/the-price-of-everything-appears-to-be-rising-as-inflation-grips-america-post-pandemic/"
[[redirects]]
  from = "/ihop-aid-veterans-families-throughout-november"
  to = "/news/ihop-aid-veterans-families-throughout-november/"
[[redirects]]
  from = "/news/black-friday"
  to = "/news/black-friday/"
[[redirects]]
  from = "/1-trillion-holiday-retail-sales"
  to = "/news/1-trillion-holiday-retail-sales/"
[[redirects]]
  from = "/thanksgiving-black-friday-2017-become-one-busiest-online-shopping-weeks-history"
  to = "/news/thanksgiving-black-friday-2017-become-one-busiest-online-shopping-weeks-history/"
[[redirects]]
  from = "/four-ways-marketing-provides-value"
  to = "/news/four-ways-marketing-provides-value/"
[[redirects]]
  from = "/thomas-j-henry-continues-turkey-giveaway-tradition/"
  to = "/news/thomas-j-henry-continues-turkey-giveaway-tradition/"
[[redirects]]
  from = "/jersey-advertising-arrives-nba/"
  to = "/news/jersey-advertising-arrives-nba/"
[[redirects]]
  from = "/agency-news/pm-group-supports-100-club/"
  to = "/news/agency-donates-10000-to-100-club/"
[[redirects]]
  from = "/agency-news/*"
  to = "/news/:splat/"

