[build]
  Functions = "lambda"
  Command = "npm run build && npm run build:lambda"
[[redirects]]
  from = "/agency-news"
  to = "/news"
[[redirects]]
  from = "/capabilities"
  to = "/expertise"
[[redirects]]
  from = "/agency-news/*"
  to = "/news/:splat"