[build]
  publish= "public"
  Command = "npm run build"
# [functions]
#   directory = "lambda"
# [dev]
#   functions = "src/lambda"
#   functionsPort = "7000"
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  baseUrl = "https://thepmgrp.com"
  trailingSlash = true
  exclude = [
    # By file Path
    "\\/news\\/\\S+"
  ]
[[plugins]]
    package = "@netlify/plugin-gatsby"
[[redirects]]
  from = "/agency-news"
  to = "/news/"
[[redirects]]
  from = "/works"
  to = "/our-work/"
[[redirects]]
  from = "/capabilities"
  to = "/expertise/"
[[redirects]]
  from = "/agency-news/drive-away-for-education-2021/"
  to = "/news/drive-away-for-education-fundraiser-aims-to-assist-50000-children-this-year/"
[[redirects]]
  from = "/agency-news/sjrc-texas/"
  to = "/news/making-a-difference-in-san-antonio-sjrc/"
[[redirects]]
  from = "/agency-news/us-inflation-rises/"
  to = "/news/the-price-of-everything-appears-to-be-rising-as-inflation-grips-america-post-pandemic/"
[[redirects]]
  from = "/agency-news/pm-group-supports-100-club/"
  to = "/news/agency-donates-10000-to-100-club/"
[[redirects]]
  from = "/agency-news/*"
  to = "/news/:splat"
