[build]
  Functions = "lambda"
  Command = "gatsby build && npm run build:lambda"

[build.environment]
  GF_CONSUMER_KEY="ck_4682363401ebb5212418f97de9afe685169c5ea8"
  GF_CONSUMER_SECRET="cs_83724c807ca617c0b44e9d19fd458f1a5096571e"
  LAMBDA_ENDPOINT="https://thepmgrp.netlify.app/.netlify/functions/new-gf-entry"
  BASE_URL="http://thepmgroup.flywheelsites.com"
  HTTPBASICAUTH_USERNAME="pm-group"
  HTTPBASICAUTH_PASSWORD="website"